spring:
  application:
    name: capstone_backend

  datasource:
    username: brightforge
    password: root
    url: jdbc:postgresql://localhost:5437/brightforge_db

  servlet:
    multipart:
      max-file-size: 10MB

